import { Router } from "express";
import { getCompanies, getLogs, getReport, downloadApp } from "../controllers/baseControllers.js";
import { getDamages, postDamage, putDamage, removeDamage } from "../controllers/damageController.js";
import { getDispatches, getDispatchProductionTotals, postDispatch } from "../controllers/dispatchController.js";
import { getEntries, getNextBatch, postEntry, putEntry, removeEntry } from "../controllers/entryController.js";
import { getSkus, postSku, putSku, removeSku } from "../controllers/skuController.js";
import { getPermissions, getRoleDefinitions, getUsers, patchUserRole, postRoleDefinition } from "../controllers/userController.js";
import { requireAuth, requirePermission } from "../middleware/auth.js";
import { authRoutes } from "./authRoutes.js";
import { asyncHandler } from "../utils/asyncHandler.js";

export const routes = Router();

routes.get("/health", (_req, res) => res.json({ ok: true }));
routes.get("/favicon.ico", (_req, res) => res.status(204).send());
routes.use("/auth", authRoutes);

routes.use(requireAuth);
routes.get("/companies", asyncHandler(getCompanies));
routes.get("/sku", asyncHandler(getSkus));
routes.post("/sku", requirePermission("ADMIN"), asyncHandler(postSku));
routes.put("/sku/:id", requirePermission("ADMIN"), asyncHandler(putSku));
routes.delete("/sku/:id", requirePermission("ADMIN"), asyncHandler(removeSku));
routes.post("/entries", requirePermission("PRODUCTION"), asyncHandler(postEntry));
routes.get("/entries", requirePermission("PRODUCTION"), asyncHandler(getEntries));
routes.get("/entries/next-batch", requirePermission("PRODUCTION"), asyncHandler(getNextBatch));
routes.put("/entries/:id", requirePermission("ADMIN"), asyncHandler(putEntry));
routes.delete("/entries/:id", requirePermission("ADMIN"), asyncHandler(removeEntry));
routes.post("/damages", requirePermission("PRODUCTION"), asyncHandler(postDamage));
routes.get("/damages", requirePermission("PRODUCTION"), asyncHandler(getDamages));
routes.put("/damages/:id", requirePermission("ADMIN"), asyncHandler(putDamage));
routes.delete("/damages/:id", requirePermission("ADMIN"), asyncHandler(removeDamage));
routes.post("/dispatches", requirePermission("DISPATCH"), asyncHandler(postDispatch));
routes.get("/dispatches", requirePermission("DISPATCH"), asyncHandler(getDispatches));
routes.get("/dispatches/production-totals", requirePermission("DISPATCH"), asyncHandler(getDispatchProductionTotals));
routes.get("/logs", requirePermission("LOGS"), asyncHandler(getLogs));
routes.get("/reports", requirePermission("REPORTS"), asyncHandler(getReport));
routes.get("/download-app", asyncHandler(downloadApp));
routes.get("/users", requirePermission("ADMIN"), asyncHandler(getUsers));
routes.patch("/users/:id/role", requirePermission("ADMIN"), asyncHandler(patchUserRole));
routes.get("/roles", requirePermission("ADMIN"), asyncHandler(getRoleDefinitions));
routes.post("/roles", requirePermission("ADMIN"), asyncHandler(postRoleDefinition));
routes.get("/permissions", requirePermission("ADMIN"), asyncHandler(getPermissions));
